# Memahami apa itu penambangan data

## Pengertian

penambangan data adalah teknik berbantuan komputer yang digunakan dalam analitik untuk memproses dan mengeksplorasi set data besar. dengan alat dan metode yang terdapat pada penambangan data suatu organisasi dapat meenemukan pola dan hubungan tersembunyi dalam data mereka.

Bunga iris memiliki beberapa jenis, untuk membedakan setiap jenis nya kita harus tau ciri-ciri nya. Disini kita akan mengetahui perbedaan dari setiap jenis bunga iris kita membedakannya dengan ukuran dari:

- Sepal Lenght Cm

- Sepal Width Cm

- Petal Length Cm

- Petal Width Cm

# Memahami data

## dataset iris

dalam matakuliah ini kita akan melakukan pengolahan data dari dataset bunga iris. Bunga ini adalah tanaman yang memiliki keindahan warna dan bentuk yang menarik. Tanaman ini biasa digunakan sebagai tanaman hias.

### Tools yang digunakan untuk melakukan inisialisasi

In [1]:
import pandas as pd
import seaborn as sns
import numpy as np

# Mengumpulkan Data

### MEMANGGIL DATA DARI MYSQL

In [2]:
df_sql = _deepnote_execute_sql('SELECT * FROM `Iris`.`tableName`', 'SQL_1A83F58B_A5D2_4F2B_AE17_AD1E5AAF843F', audit_sql_comment='', sql_cache_mode='cache_disabled')
df_sql

      Id  SepalLengthCm  SepalWidthCm         Species
0      1            5.1           3.5     Iris-setosa
1      2            4.9           3.0     Iris-setosa
2      3            4.7           3.2     Iris-setosa
3      4            4.6           3.1     Iris-setosa
4      5            5.0           3.6     Iris-setosa
..   ...            ...           ...             ...
145  146            6.7           3.0  Iris-virginica
146  147            6.3           2.5  Iris-virginica
147  148            6.5           3.0  Iris-virginica
148  149            6.2           3.4  Iris-virginica
149  150            5.9           3.0  Iris-virginica

[150 rows x 4 columns]

### PENJELASAN

Data yang di ambil dari sql hanya memiliki 2 fitur yaitu:

- Sepal Lenght Cm

- Sepal Widht Cm

Untuk mengakses data dari database sql yang perlu dilakukan adalah menuliskan perintah sql dengan memanggil nama dari database yang ada di integrasi lalu nama dari table tersebut seperti contoh diatas

## Memahami Data

### MEMANGGIL DATA DARI POSTGRESQL

In [3]:
df_postgre = _deepnote_execute_sql('SELECT * FROM public.tablename', 'SQL_92267C34_4DCE_4E8B_BF58_83849AF3DB64', audit_sql_comment='', sql_cache_mode='cache_disabled')
df_postgre

      id  petallengthcm  petalwidthcm         species
0      1            1.4           0.2     Iris-setosa
1      2            1.4           0.2     Iris-setosa
2      3            1.3           0.2     Iris-setosa
3      4            1.5           0.2     Iris-setosa
4      5            1.4           0.2     Iris-setosa
..   ...            ...           ...             ...
145  146            5.2           2.3  Iris-virginica
146  147            5.0           1.9  Iris-virginica
147  148            5.2           2.0  Iris-virginica
148  149            5.4           2.3  Iris-virginica
149  150            5.1           1.8  Iris-virginica

[150 rows x 4 columns]

### PENJELASAN

Data yang di ambil dari database ini juga memiliki 2 fitu saja yaitu:

- Petal Lenght Cm

- Petal Widht Cm

Perintah yang di gunakan sama seperti perintah sql saat mengakses data dari mysql namun bedanya untuk di postgresql database nya berada di public lalu nama dari table tersebut.

# Menggabungkan data

### GABUNG 2 DATABASE BERBEDA

In [4]:
df = pd.concat([df_sql.drop(['Species'], axis=1), df_postgre.drop(['id'], axis=1)], axis=1, join='inner')

df

,Id,SepalLengthCm,SepalWidthCm,petallengthcm,petalwidthcm,species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

### PENJELASAN

Dalam penggabungan 2 dataframe ini kita akan gunakan library yang ada pada pandas perintah untuk penjelasan lebih detailnya dari fungsi code dia adalah:

1. pd.concat: Ini adalah fungsi dari pustaka pandas yang digunakan untuk menggabungkan DataFrames. Ini bekerja dengan menggabungkan DataFrames baik secara vertikal (baris) atau horizontal (kolom) berdasarkan sumbu yang ditentukan.

2. [df_sql.drop(['Species'], axis=1), df_postgre.drop(['id'], axis=1)]: Di sini, kita menggunakan metode .drop() untuk menghapus kolom tertentu dari masing-masing DataFrame sebelum penggabungan dilakukan. Dalam df_sql, kolom 'Species' dihapus, sedangkan dalam df_postgre, kolom 'id' dihapus. Penggunaan axis=1 menunjukkan bahwa kita menghapus kolom, bukan baris.

3. axis=1: Parameter ini menunjukkan bahwa kita ingin menghapus kolom, bukan baris. Ketika disetel ke 1, metode .drop() akan menghapus kolom. Jika diatur ke 0, itu akan menghapus baris.

4. axis=0 (opsional): Meskipun tidak disertakan dalam perintah yang Anda berikan, itu akan menjadi nilai defaultnya. Ini hanya untuk memberikan pemahaman tambahan bahwa jika Anda ingin menghapus baris, Anda akan menggunakan axis=0.

5. join='inner': Parameter ini menentukan tipe penggabungan yang digunakan. 'inner' berarti bahwa hanya baris dengan kunci yang cocok di kedua DataFrame akan dipertahankan. Jadi, hasil akhir akan berisi hanya baris-baris yang memiliki kunci yang sama di kedua DataFrame.

# DESKRIPSI DATA

## FITUR

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   petallengthcm  150 non-null    float64
 4   petalwidthcm   150 non-null    float64
 5   species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

### PENJELASAN

dengan menggunakan perintah df.info() untuk mengetahui info apa saja yang ada pada dataset. Informasi yang dapat ditampilkan dengan perintah ini adalah:

1. RangeIndex: Menunjukkan bahwa indeks Data frame adalah dari 0 hingga 149, yang menandakan bahwa DataFrame ini memiliki 150 baris.

2. Data columns: Ini adalah daftar kolom yang ada di Data Frame, disertakan dengan informasi tambahan tentang jumlah nilai non-null dan tipe data masing-masing kolom.

3. Coloumn: Ini menampilkan data apa saja yang ada pada Data Frame tersebut seperti contoh Id,SepalLengthCm,SepalWidthCm, PetalLengthCm,PetalWidthCm,dan Species.

4. Dtype: tipe data dari setiap kolom tersebut

untuk mengetahui berapa banyak species dari bunga iris yang ada pada data frame kita bisa menggunakan perintah:

In [6]:
df.value_counts('species')

species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

dari data yang ditampilkan diatas sudah kita ketahui jika data frame tersebut dapat diketahui jika ada 3 jenis species, yaitu:

1. Iris Setosa

2. Iris Versicolor

3. Iris Virginica

### MISSING VALUE

In [7]:
df.loc[df["Id"] == 2, 'SepalLengthCm'] = None
df.loc[df["Id"] == 7, 'SepalLengthCm'] = None
df.loc[df["Id"] == 10, 'SepalLengthCm'] = None

df

,Id,SepalLengthCm,SepalWidthCm,petallengthcm,petalwidthcm,species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,NaN,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

### MENAMPILKAN DATA YANG MEMILIKI MISSING VALUE

In [8]:
df_3 = _deepnote_execute_sql('', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled')
df_3

In [9]:
df.isnull().sum()

Id               0
SepalLengthCm    3
SepalWidthCm     0
petallengthcm    0
petalwidthcm     0
species          0
dtype: int64

perintah ini digunakan untuk menampilkan semua jumlah data yang kosong dari data frame diatas.

### PRA-PEMROSESAN DATA

Ada 4 tahap untuk melakukan pra-pemrosesan data, yaitu:

1. Membersihkan data (data cleaning)

- tujuan dari membersihkan data yaitu untuk menyeleksi dan menghapus data yang tidak relevan, tidak lengkap, atau tidak akurat. Ini digunakan untuk mengurangi kesalahan interpretasi data

2. Penggabungan data (data integration)

- proses ini dilakukan untuk menggabungkan data dari berbagai sumber menjadi data frame. Pastikan bahwa sumber data yang di ambil memiliki format yang sama dengan data yang kita miliki.

3. Transformasi Data (Data Transformation)

- proses ini digunakan untuk mentransformasi dari dataset yang kita ambil dari sumber lain. proses ini dilakukan karena ada kemungkinan bahwa dataset yang kita ambil memiliki perbedaan format.

4. Pengurangan Data (Data Reduction)

ada beberapa cara dalam melakukan pengurangan data, yaitu:

- Mengurangi dimensi: Mengurangi jumlah fitur atau variabel yang digunakan.

- Pengurangan Jumlah Data: Mengambil sampel data yang lebih kecil.

- Kompresi Data: Mengurangi ukuran data tanpa menghilangkan informasi penting.

# Data Cleaning

### A.Seleksi Fitur

In [10]:
df = df.drop(['Id'], axis=1)

df

     SepalLengthCm  SepalWidthCm  petallengthcm  petalwidthcm         species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              NaN           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

Seleksi fitur dilakukan untuk menghilangkan kolom dan fitur yang tidak relevan atau tidak diperlukan untuk analisis atau perhitungan lebih lanjut.

 Dalam hal ini kolom “Id” dihilangkan karena  tidak diperlukan dalam proses pemodelan atau perhitungan.

### B. Merubah nama kolom

In [11]:
df = df.rename(columns={'Sepal Length' : 'Sepal_Length', 'Sepal Width' : 'Sepal_Width', 'Petal Length' : 'Petal_Length', 'Petal Width' : 'Petal_Width'})

df.head(5)

   SepalLengthCm  SepalWidthCm  petallengthcm  petalwidthcm      species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            NaN           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

### Hal yang Perlu di Perhatikan dalam pengubahan nama

Penamaan Kolom:

dalam proses penggantian nama kolom kita dapat menggunakan method atau fungsi yang sudah tersedia di library pandas untuk mengganti nama dari setiap kolom. Contoh nya dalam pandas kita bisa menggunakan fungsi rename().

Menggunakan nama yang lebih deskriptif:

Agar mempermudah dalam proses analisis data kita perlunya untuk memberikan nama yang lebih jelas dan deskriptif untuk setiap kolomnya.

Singkat dan jelas:

untuk mempermudah pastikan untuk memberikan nama yang jelas dan singkat.

Hindari spasi dan karakter khusus:

Gunakan format yang konsisten dan hindari spasi ataupun karakter khusus dalam penamaan kolom. Jika memang di perlukan ganti spasi dengan garis bawah.

### C. Menghapus baris duplikat

1. cek jumlah baris dan kolom

In [12]:
df.shape

(150, 5)

2. cek jumlah baris dan kolom yang memiliki data duplikat

In [13]:
duplicate_rows_df = df[df.duplicated()]
print('number of duplicate rows : ', duplicate_rows_df.shape)

number of duplicate rows :  (2, 5)

Dengan perintah code diatas kita sudah mengetahui bahwa terdapat data yang sama yaitu berjumlah 2 baris data yang sama

3. hapus duplikasi data

In [14]:
df = df.drop_duplicates()
print('number of rows after drop duplicated rows', df.shape)

number of rows after drop duplicated rows (148, 5)

Dari hasil output diatas kita bisa mengetahui bahwa dari data awal yang berjumlah 150 data berkurang menjadi 148 baris data. Hal ini menandakan bahwa data duplikasi berhasil kita hapus.

### Penanganan missing value dengan menggunakan  metode mean atau nilai rata-rata

pada proses ini kita akan melakukan pengisian missing value atau data yang tidak memiliiki nilai dengan nilai rata-rata dalam metode ini kita akan melakukan penjumlahan nilai fitur lalu nilai tersebut akan di bagi dengan jumlah baris. Dengan ini nilai hasil tersebut akan menjadi nilai rata-ratanya.

untuk melakukan pengisian missing value ini langkah-langkah yang perlu kita lakukan adalah:

- berikut merupakan data awal dari dataset yang memiliki missing value

In [15]:
df

     SepalLengthCm  SepalWidthCm  petallengthcm  petalwidthcm         species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              NaN           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[148 rows x 5 columns]

1. Simpan atau copy data frame pada variabel lain

2. Cari nilai mean atau nilai rata-ratanya seperti yang di jelaskan di atas tadi

3. Lakukan inputasi missing value dengan nilai yang sudah di hitung tadi.

In [16]:
df_mean = df.copy(deep=True)

mean = round(df_mean['SepalLengthCm'].mean(), 1)
print('nilai mean adalah = ', mean)

df_mean['SepalLengthCm'].fillna(mean, inplace=True)

df_mean

nilai mean adalah =  5.9

     SepalLengthCm  SepalWidthCm  petallengthcm  petalwidthcm         species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              5.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[148 rows x 5 columns]

dari langkah-langkah diatas dan bukti hasil dari inputasi kita bisa lihat bahwa yang tadinya terdapat missing value sekarang sudah kita ganti dengan nilai rata-rata atau mean. Jadi

### Penanganan missing value dengan menggunakan metode K Nearest Neighbor(KNN)

Metode ini merupakan proses dimana kita akan mencaari tetangga terdekat dari data yang ingin di prediksi, dan kemudian membandingkan kelas dari tetangga tersebut untuk memprediksikan kelas dari data yang baru. Jadi, kita dapat menggambarkan KNN sebagai teknik yang menggunakan jumlah tetangga terdekat untuk memprediksi klasifikasi data baru. Penjelasan lebih rinci tentang cara kerjanya dapat ditemukan dibawah ini.

$d(P,Q) = \sqrt{\sum_{i=1}^{n} (p_{i} - q_{i})^2}$

$d(P,Q) = \sqrt{(p_{1} - q_{1})^2 + (p_{2} - q_{2})^2 + ... + (p_{n} - q_{n})^2}$

### Inputasi missing value dengan menggunakan KNN Inputer

Langkah-langkah dalam melakukan inputasi missing value menggunakan KNN

1. Lakukan copy data frame

2. Simpan class species kedalam variabel baru

3. hapus kolom yang tidak diperlukan

4. Lakukan inisiasi KNN

5. gabung hasil dari inputan dengan class objek

In [17]:
from sklearn.impute import KNNImputer

df_knn = df.copy(deep=True)

df_species = df_knn[['species']]

list_species = df_species.values.tolist()

df_knn = df_knn.drop(['species'], axis=1)

imputer = KNNImputer(n_neighbors=3)

result = imputer.fit_transform(df_knn)

result = result.tolist()

for index in range(len(result)):
    result[index].append(list_species[index][0])

df_knn = pd.DataFrame(result, columns=['SepalLength', 'SepalWidth','PetalLength','PetalWidth','Species'])
df_knn

     SepalLength  SepalWidth  PetalLength  PetalWidth         Species
0       5.100000         3.5          1.4         0.2     Iris-setosa
1       4.533333         3.0          1.4         0.2     Iris-setosa
2       4.700000         3.2          1.3         0.2     Iris-setosa
3       4.600000         3.1          1.5         0.2     Iris-setosa
4       5.000000         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
143     6.700000         3.0          5.2         2.3  Iris-virginica
144     6.300000         2.5          5.0         1.9  Iris-virginica
145     6.500000         3.0          5.2         2.0  Iris-virginica
146     6.200000         3.4          5.4         2.3  Iris-virginica
147     5.900000         3.0          5.1         1.8  Iris-virginica

[148 rows x 5 columns]

Dari data diatas kita bisa lihat hasil dari pengisian data menggunakan KNNImputer

## Deteksi oulier (Local Outlier Factor)

### Teori konsep local outlier factor

Local Outlier Factor (LOF) adalah sebuah metode dalam data mining yang digunakan untuk mendeteksi anomali dalam data. Metode ini dikembangkan oleh Markus M. Breunig, Hans-Peter Kriegel, Raymond T. Ng, dan Jörg Sander pada tahun 2000.

Konsep utama dari LOF adalah mengukur "ketidakbiasan lokal" dari sebuah titik data terhadap tetangga-tetangganya. LOF membandingkan kerapatan titik data pada lokasi tersebut dengan kerapatan tetangga-tetangganya. Jika titik data tersebut memiliki kerapatan yang jauh lebih rendah dibandingkan dengan tetangga-tetangganya, maka dapat disimpulkan bahwa titik tersebut merupakan outlier.

Berikut adalah langkah-langkah utama dalam menghitung LOF:

- Menghitung Jarak: Jarak antara setiap titik data dengan titik lainnya dalam dataset harus dihitung. Jarak ini bisa dihitung menggunakan metrik jarak seperti Euclidean distance, Manhattan distance, atau metrik jarak lainnya tergantung pada jenis data dan kasus penggunaan.

- Menghitung Kerapatan: Kerapatan dari setiap titik data juga perlu dihitung. Kerapatan biasanya dihitung menggunakan metode seperti k-nearest neighbors (KNN) di sekitar titik data.

- Menghitung Local Reachability Density (LRD): LRD adalah ukuran invers dari kerapatan lokal. Untuk setiap titik data, LRD dihitung sebagai rata-rata invers dari jarak antara titik data dan tetangga-tetangganya.

- Menghitung Local Outlier Factor (LOF): LOF dari sebuah titik data dihitung dengan membandingkan LRD dari titik data tersebut dengan LRD dari tetangga-tetangganya. LOF didefinisikan sebagai rasio antara LRD titik data dan rata-rata LRD dari tetangga-tetangganya.

- Interpretasi: Titik-titik dengan LOF yang tinggi kemungkinan besar merupakan outlier dalam dataset.

### Menghitung manual local outlier factor

menggunakan 10 data dengan isinya numerik 10 baris 3 kolom k=3 p=2 (euclidian distance)

<img src="image-20240328-094151.png" width="" align="" />

### Menghitung menggunakan python (Scikit Learn)

In [18]:
from sklearn.neighbors import LocalOutlierFactor

data_out = [
    [5, 1, 2],
    [4, 3, 3],
    [6, 3, 11],
    [4, 9, 1],
    [7, 3, 1],
    [6, 3, 12],
    [8, 10, 2],
    [4, 4, 4],
    [7, 2, 3],
    [7, 2, 11]
]

lof = LocalOutlierFactor(n_neighbors=3)

lof.fit_predict(data_out)

lof_scores = -lof.negative_outlier_factor_.round(3)

print("LOF Scores:", lof_scores)

LOF Scores: [1.012 0.981 1.403 1.588 0.99  1.403 1.726 1.079 0.99  1.403]

### Implementasi Local Outlier Factor pada data iris

In [19]:
df_iris = pd.concat([df_sql.drop(['Id','Species'], axis=1), df_postgre.drop(['id'], axis=1)], axis=1, join='inner')
df_iris = df_iris.rename(columns={'SepalLengthCm' : 'SepalLength', 'SepalWidthCm' : 'SepalWidth', 'petallengthcm' : 'PetalLength', 'petalwidthcm' : 'PetalWidth'})

iris_species = df_iris[['species']]

iris_species = df_iris[['species']]

lof = LocalOutlierFactor(n_neighbors=4, contamination=0.1)
outlier_labels = lof.fit_predict(df_iris.drop(['species'], axis=1))

df_iris['Outlier'] = outlier_labels
df_iris['Species'] = iris_species

df_iris

,SepalLength,SepalWidth,PetalLength,PetalWidth,species,Outlier,Species
0,5.1,3.5,1.4,0.2,Iris-setosa,1,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa,1,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa,1,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa,1,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa,1,Iris-setosa
...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica,1,Iris-virginica
146,6.3,2.5,5.0,1.9,Iris-virginica,1,Iris-virginica
147,6.5,3.0,5.2,2.0,Iris-virginica,1,Iris-virginica
148,6.2,3.4,5.4,2.3,Iris-virginica,1,Iris-virginica
149,5.9,3.0,5.1,1.8,Iris-virginica,1,Iris-virginica

In [20]:
df_4 = _deepnote_execute_sql('SELECT * FROM `defaultdb`.`dataset`', 'SQL_1A83F58B_A5D2_4F2B_AE17_AD1E5AAF843F', audit_sql_comment='', sql_cache_mode='cache_disabled')
df_4

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

# Naive Bayes

Naive Bayes adalah teknik peramalan probabilistik sederhana sesuai dengan pelaksanaan teorema Bayes (hukum bayes) menggunakan perkiraan independensi yang kuat. Kelebihan dari pada metode ini ialah hanya memerlukan sedikit data latih dengan tujuan memastikan parameter yang diharapkan pada langkah klasifikasi.

Pendekatan Naïve Bayes digunakan untuk analisis data. Ini adalah pengklasifikasi probabilitas dasar yang menggunakan Teorema Bayes dengan asumsi independensi yang tinggi.

## Implementasi pada excel

<img src="implementasi naive bayes.PNG" width="" align="" />

## implementasi pada data iris

In [21]:
df_sepal = _deepnote_execute_sql('SELECT * FROM Iris.tableName', 'SQL_1A83F58B_A5D2_4F2B_AE17_AD1E5AAF843F', audit_sql_comment='', sql_cache_mode='cache_disabled')
df_sepal

      Id  SepalLengthCm  SepalWidthCm         Species
0      1            5.1           3.5     Iris-setosa
1      2            4.9           3.0     Iris-setosa
2      3            4.7           3.2     Iris-setosa
3      4            4.6           3.1     Iris-setosa
4      5            5.0           3.6     Iris-setosa
..   ...            ...           ...             ...
145  146            6.7           3.0  Iris-virginica
146  147            6.3           2.5  Iris-virginica
147  148            6.5           3.0  Iris-virginica
148  149            6.2           3.4  Iris-virginica
149  150            5.9           3.0  Iris-virginica

[150 rows x 4 columns]

In [22]:
df_petal = _deepnote_execute_sql('SELECT * FROM public.tablename', 'SQL_92267C34_4DCE_4E8B_BF58_83849AF3DB64', audit_sql_comment='', sql_cache_mode='cache_disabled')
df_petal

      id  petallengthcm  petalwidthcm         species
0      1            1.4           0.2     Iris-setosa
1      2            1.4           0.2     Iris-setosa
2      3            1.3           0.2     Iris-setosa
3      4            1.5           0.2     Iris-setosa
4      5            1.4           0.2     Iris-setosa
..   ...            ...           ...             ...
145  146            5.2           2.3  Iris-virginica
146  147            5.0           1.9  Iris-virginica
147  148            5.2           2.0  Iris-virginica
148  149            5.4           2.3  Iris-virginica
149  150            5.1           1.8  Iris-virginica

[150 rows x 4 columns]

In [23]:
df = pd.concat([df_sepal.drop(['Species'], axis=1), df_petal.drop(['id'], axis=1)], axis=1, join='inner')

df

,Id,SepalLengthCm,SepalWidthCm,petallengthcm,petalwidthcm,species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [24]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.datasets import load_iris

iris = load_iris()
X = iris.data
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("================== DATA X_train ==================")
print(pd.DataFrame(X_train, columns=iris.feature_names))

print("================== DATA X_test ==================")
print(pd.DataFrame(X_test, columns=iris.feature_names))

print("================== DATA Y_train ==================")
print(pd.DataFrame(y_train, columns=['Species']))

print("================== DATA Y_test ==================")
print(pd.DataFrame(y_test, columns=['Species']))

clf = GaussianNB()
clf.fit(X_train, y_train)

predictions = clf.predict(X_test)

accuracy = np.mean(predictions == y_test)
print("Akurasi:", accuracy)

new_data = np.array([[5.1, 3.5, 1.4, 0.2], [7, 3.2, 4.7, 1.4], [7.2, 3.6, 6.1, 2.5]])

predicted_classes = clf.predict(new_data)

for i, predicted_class in enumerate(predicted_classes):
    print("Data baru ke-", i, "kelas yang diprediksi:", iris.target_names[predicted_class])

================== DATA X_train ==================
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  4.6               3.6                1.0               0.2
1                  5.7               4.4                1.5               0.4
2                  6.7               3.1                4.4               1.4
3                  4.8               3.4                1.6               0.2
4                  4.4               3.2                1.3               0.2
..                 ...               ...                ...               ...
115                6.1               2.8                4.0               1.3
116                4.9               2.5                4.5               1.7
117                5.8               4.0                1.2               0.2
118                5.8               2.6                4.0               1.2
119                7.1               3.0                5.9               2.1

[120 rows x 4 columns]
================== DATA X_test ==================
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                 6.1               2.8                4.7               1.2
1                 5.7               3.8                1.7               0.3
2                 7.7               2.6                6.9               2.3
3                 6.0               2.9                4.5               1.5
4                 6.8               2.8                4.8               1.4
5                 5.4               3.4                1.5               0.4
6                 5.6               2.9                3.6               1.3
7                 6.9               3.1                5.1               2.3
8                 6.2               2.2                4.5               1.5
9                 5.8               2.7                3.9               1.2
10                6.5               3.2                5.1               2.0
11                4.8               3.0                1.4               0.1
12                5.5               3.5                1.3               0.2
13                4.9               3.1                1.5               0.1
14                5.1               3.8                1.5               0.3
15                6.3               3.3                4.7               1.6
16                6.5               3.0                5.8               2.2
17                5.6               2.5                3.9               1.1
18                5.7               2.8                4.5               1.3
19                6.4               2.8                5.6               2.2
20                4.7               3.2                1.6               0.2
21                6.1               3.0                4.9               1.8
22                5.0               3.4                1.6               0.4
23                6.4               2.8                5.6               2.1
24                7.9               3.8                6.4               2.0
25                6.7               3.0                5.2               2.3
26                6.7               2.5                5.8               1.8
27                6.8               3.2                5.9               2.3
28                4.8               3.0                1.4               0.3
29                4.8               3.1                1.6               0.2
================== DATA Y_train ==================
     Species
0          0
1          0
2          1
3          0
4          0
..       ...
115        1
116        2
117        0
118        1
119        2

[120 rows x 1 columns]
================== DATA Y_test ==================
    Species
0         1
1         0
2         2
3         1
4         1
5         0
6         1
7         2
8         1
9         1
10        2
11        0
12        0
13        0
14        0
15        1
16        2
17        1
18        1
19        2
20        0
21        2
22        0
23        2
24        2
25        2
26        2
27        2
28        0
29        0
Akurasi: 1.0
Data baru ke- 0 kelas yang diprediksi: setosa
Data baru ke- 1 kelas yang diprediksi: versicolor
Data baru ke- 2 kelas yang diprediksi: virginica

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=10945847-e31e-4133-a073-8fa6c5986d5c' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' > </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>